site_name: {{ cookiecutter.project_name }}
nav:
  - Home: index.md
  - Refrence: api.md
theme:
  name: material
repo_name: alpine-data/{{ cookiecutter.project_name }}
repo_url: https://github.com/alpine-data/{{ cookiecutter.project_name }}
edit_uri: edit/main/docs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
markdown_extensions:
  - mkdocs-click
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css